name: "Build sysext: swtpm"

env:
  SYSEXT: "swtpm"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'sysext.just'
      - 'swtpm/**'
      - '.github/workflows/swtpm.yml'
  push:
    branches:
      - main
    paths:
      - 'sysext.just'
      - 'swtpm/**'
      - '.github/workflows/swtpm.yml'

permissions: read-all

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-sysext:
    runs-on: "ubuntu-24.04"
    container:
      image: "quay.io/fedora/fedora:41"
      options: "--privileged --security-opt label=disable --user 0:0"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          dnf install -y erofs-utils just selinux-policy-targeted 'dnf-command(download)' cpio wget

      - name: Build sysext
        run: |
          cd ${SYSEXT}
          just
