name: "Build all sysexts for a release"

env:
  GH_TOKEN: ${{ github.token }}

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/sysexts-release.yml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sysexts-release.yml'
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

# Needed to allow creating a release
permissions:
  contents: write

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-release-sysexts:
    runs-on: "ubuntu-24.04"
    strategy:
      matrix:
        release: ['40', '41']
    container:
      image: "quay.io/fedora/fedora:${{ matrix.release }}"
      options: "--privileged --security-opt label=disable --user 0:0"
    steps:
      - name: Install tools
        run: |
          dnf install -y \
            erofs-utils \
            just \
            cpio \
            wget \
            git
          if [[ "$(dnf --version | head -1 | cut -f1 -d\ )" == "dnf5" ]]; then
            dnf install -y dnf5-plugins
            dnf config-manager addrepo --from-repofile="https://cli.github.com/packages/rpm/gh-cli.repo"
          else
            dnf install -y 'dnf-command(config-manager)'
            dnf config-manager --add-repo "https://cli.github.com/packages/rpm/gh-cli.repo"
          fi
          dnf install -y gh --repo gh-cli

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build sysexts
        run: |
          for d in $(ls -d ./*/); do
            pushd $d
            just check "quay.io/fedora-ostree-desktops/kinoite:41" || break
            just default "quay.io/fedora-ostree-desktops/kinoite:41"
            popd
          done

      - name: Create a release
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'
        run: |
          sysexts=()
          for d in $(ls -d ./*/); do
            name="$(basename $d)"
            sysexts+=("./$name/$name.raw")
          done
          git config --global --add safe.directory "${PWD}"
          gh release delete --cleanup-tag --yes "f${RELEASE}" || true
          # TODO: Handle --latest
          gh release create \
            --title "Fedora ${RELEASE} sysexts" \
            --notes "System extensions for Fedora ${RELEASE}" \
            "f${RELEASE}" \
            "${sysexts[@]}"
        env:
          RELEASE: ${{ matrix.release }}
